[package]
name = "ansi_color_constants"
version = "1.0.0"
edition = "2021"

description = "Named constants for ANSI codes in Windows Terminal."
readme = "readme.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Satellile/ansi_color_constants"


[dependencies]
